### ISSUE TITLE
def bezierslopeatt 

### ISSUE THREAD

**Issue by FireMarshmellow** [UmerSoftwares/Draw-3D#1]
I've been trying to use your plugin but keep getting this error
and everywhere I look is said its a python2 problem because its dead
File "umer_plotter.py", line 54
    def bezierslopeatt(((bx0,by0),(bx1,by1),(bx2,by2),(bx3,by3)),t):
                       ^
SyntaxError: invalid syntax

**Comment by UmerSoftwares** [comment]
What version of inkscape are you using?
